import { PlanSummary } from "types/app";

// list of all current plans
export const plans: PlanSummary[] = [
  { id: "c25k", name: "Couch to 5K", type: "5K", coach: "Couch to 5K" },
  { id: "c25k_rbp", name: "Couch to 5K -- Runner's Blueprint", type: "5K", coach: "Couch to 5K" },
  { id: "frr_5k_01", name: "Faster Road Racing: 5K Schedule 1", type: "5K", coach: "Faster Road Racing" },
  { id: "frr_5k_02", name: "Faster Road Racing: 5K Schedule 2", type: "5K", coach: "Faster Road Racing" },
  { id: "frr_5k_03", name: "Faster Road Racing: 5K Schedule 3", type: "5K", coach: "Faster Road Racing" },
  { id: "frr_8k10k_01", name: "Faster Road Racing: 8K-10K Schedule 1", type: "10K", coach: "Faster Road Racing" },
  { id: "frr_8k10k_02", name: "Faster Road Racing: 8K-10K Schedule 2", type: "10K", coach: "Faster Road Racing" },
  { id: "frr_8k10k_03", name: "Faster Road Racing: 8K-10K Schedule 3", type: "10K", coach: "Faster Road Racing" },
  { id: "frr_15k_10m_01", name: "Faster Road Racing: 15k and 10 Miles Schedule 1", type: "15K/10M", coach: "Faster Road Racing" },
  { id: "frr_15k_10m_02", name: "Faster Road Racing: 15k and 10 Miles Schedule 2", type: "15K/10M", coach: "Faster Road Racing" },
  { id: "frr_15k_10m_03", name: "Faster Road Racing: 15k and 10 Miles Schedule 3", type: "15K/10M", coach: "Faster Road Racing" },
  { id: "frr_bt_01", name: "Faster Road Racing: Base Training 1", type: "Base", coach: "Faster Road Racing" },
  { id: "frr_bt_02", name: "Faster Road Racing: Base Training 2", type: "Base", coach: "Faster Road Racing" },
  { id: "frr_bt_03", name: "Faster Road Racing: Base Training 3", type: "Base", coach: "Faster Road Racing" },
  { id: "frr_multiple_distances_01", name: "Faster Road Racing: Multiple Distances 1", type: "Multiple Distances", coach: "Faster Road Racing" },
  { id: "frr_multiple_distances_02", name: "Faster Road Racing: Multiple Distances 2", type: "Multiple Distances", coach: "Faster Road Racing" },
  { id: "frr_multiple_distances_03", name: "Faster Road Racing: Multiple Distances 3", type: "Multiple Distances", coach: "Faster Road Racing" },
  { id: "pfitz_half_12_47", name: "Pfitzinger/Douglas: Half Marathon Schedule 1, 31 to 47 miles per Week", type: "Half Marathon", coach: "Pfitzinger/Douglas", subcategory: "Half Marathon" },
  { id: "pfitz_half_12_63", name: "Pfitzinger/Douglas: Half Marathon Schedule 2, 46 to 63 miles per Week", type: "Half Marathon", coach: "Pfitzinger/Douglas", subcategory: "Half Marathon" },
  { id: "pfitz_half_12_84", name: "Pfitzinger/Douglas: Half Marathon Schedule 3, 61 to 84 miles per Week", type: "Half Marathon", coach: "Pfitzinger/Douglas", subcategory: "Half Marathon" },
  { id: "pfitz_half_12_100", name: "Pfitzinger/Douglas: Half Marathon Schedule 4, 81 to 100 miles per Week", type: "Half Marathon", coach: "Pfitzinger/Douglas", subcategory: "Half Marathon" },
  { id: "hansons_c210k", name: "Hansons Couch Potato to 10k", type: "10K", coach: "Hansons" },
  { id: "hansons_adv_half", name: "Hansons Advanced Half Marathon", type: "Half Marathon", coach: "Hansons" },
  { id: "hansons_beg_half", name: "Hansons Beginner Half Marathon", type: "Half Marathon", coach: "Hansons" },
  { id: "higdon_adv_mara1", name: "Hal Higdon: Advanced 1", type: "Marathon", coach: "Hal Higdon" },
  { id: "higdon_adv_mara2", name: "Hal Higdon: Advanced 2", type: "Marathon", coach: "Hal Higdon" },
  { id: "higdon_int_mara1", name: "Hal Higdon: Intermediate 1", type: "Marathon", coach: "Hal Higdon" },
  { id: "higdon_int_mara2", name: "Hal Higdon: Intermediate 2", type: "Marathon", coach: "Hal Higdon" },
  { id: "higdon_nov_mara1", name: "Hal Higdon: Novice 1", type: "Marathon", coach: "Hal Higdon" },
  { id: "higdon_nov_mara2", name: "Hal Higdon: Novice 2", type: "Marathon", coach: "Hal Higdon" },
  { id: "higdon_mara3", name: "Hal Higdon: Marathon 3", type: "Marathon", coach: "Hal Higdon" },
  { id: "higdon_senior_mara", name: "Hal Higdon: Senior Marathon", type: "Marathon", coach: "Hal Higdon" },
  { id: "higdon_half3", name: "Hal Higdon: Half Marathon 3", type: "Half Marathon", coach: "Hal Higdon" },
  { id: "higdon_int_half1", name: "Hal Higdon: Half Marathon Intermediate 1", type: "Half Marathon", coach: "Hal Higdon" },
  { id: "higdon_int_half2", name: "Hal Higdon: Half Marathon Intermediate 2", type: "Half Marathon", coach: "Hal Higdon" },
  { id: "higdon_nov_half1", name: "Hal Higdon: Half Marathon Novice 1", type: "Half Marathon", coach: "Hal Higdon" },
  { id: "higdon_nov_half2", name: "Hal Higdon: Half Marathon Novice 2", type: "Half Marathon", coach: "Hal Higdon" },
  { id: "hansons_adv_mara", name: "Hansons Advanced Marathon", type: "Marathon", coach: "Hansons" },
  { id: "hansons_beg_mara", name: "Hansons Beginner Marathon", type: "Marathon", coach: "Hansons" },
  { id: "coogan_pbr_mara_up_to_65", name: "Personal Best Running: 16-Week Marathon - Up to 65 Miles per Week", type: "Marathon", coach: "Personal Best Running" },
  { id: "boston_level_one", name: "Boston Marathon Level 1 Plan", type: "Marathon", coach: "Boston Marathon Training" },
  { id: "boston_level_two", name: "Boston Marathon Level 2 Plan", type: "Marathon", coach: "Boston Marathon Training" },
  { id: "boston_level_three", name: "Boston Marathon Level 3 Plan", type: "Marathon", coach: "Boston Marathon Training" },
  { id: "boston_level_four", name: "Boston Marathon Level 4 Plan", type: "Marathon", coach: "Boston Marathon Training" },
  { id: "pfitz_12_55", name: "Pfitzinger/Douglas: Up to 55 miles per week, 12-week schedule (third edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "12-Week" },
  { id: "pfitz_12_55_4th", name: "Pfitzinger/Douglas: Up to 55 miles per week, 12-week schedule (fourth edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "12-Week" },
  { id: "pfitz_12_70", name: "Pfitzinger/Douglas: 55 to 70 Miles per Week, 12-week schedule (third edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "12-Week" },
  { id: "pfitz_12_70_4th", name: "Pfitzinger/Douglas: 55 to 70 Miles per Week, 12-week schedule (fourth edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "12-Week" },
  { id: "pfitz_12_85", name: "Pfitzinger/Douglas: 70 to 85 Miles per Week, 12-week schedule (third edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "12-Week" },
  { id: "pfitz_12_85_4th", name: "Pfitzinger/Douglas: 70 to 85 Miles per Week, 12-week schedule (fourth edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "12-Week" },
  { id: "pfitz_12_more_than_85", name: "Pfitzinger/Douglas: More Than 85 Miles per Week, 12-week schedule (third edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "12-Week" },
  { id: "pfitz_12_more_than_85_4th", name: "Pfitzinger/Douglas: More Than 85 Miles per Week, 12-week schedule (fourth edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "12-Week" },
  { id: "pfitz_18_55", name: "Pfitzinger/Douglas: Up to 55 miles per week, 18-week schedule (third edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "18-Week" },
  { id: "pfitz_18_55_4th", name: "Pfitzinger/Douglas: Up to 55 miles per week, 18-week schedule (fourth edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "18-Week" },
  { id: "pfitz_18_70", name: "Pfitzinger/Douglas: 55 to 70 Miles per Week, 18-week schedule (third edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "18-Week" },
  { id: "pfitz_18_70_4th", name: "Pfitzinger/Douglas: 55 to 70 Miles per Week, 18-week schedule (fourth edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "18-Week" },
  { id: "pfitz_18_85", name: "Pfitzinger/Douglas: 70 to 85 Miles per Week, 18-week schedule (third edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "18-Week" },
  { id: "pfitz_18_85_4th", name: "Pfitzinger/Douglas: 70 to 85 Miles per Week, 18-week schedule (fourth edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "18-Week" },
  { id: "pfitz_18_more_than_85", name: "Pfitzinger/Douglas: More Than 85 Miles per Week, 18-week schedule (third edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "18-Week" },
  { id: "pfitz_18_more_than_85_4th", name: "Pfitzinger/Douglas: More Than 85 Miles per Week, 18-week schedule (fourth edition)", type: "Marathon", coach: "Pfitzinger/Douglas", subcategory: "18-Week" },
];
